listen:
  hostname: 'localhost'
  port: 3234

webserver:
  https: false
  hostname: 'localhost'
  port: 3234

elastic-search:
  # https or http
  http: 'http'
  auth:
    username: null
    password: null
  ssl:
    # Specificy a custom CA
    ca: null
  hostname: 'localhost'
  port: 9200
  indexes:
    videos: 'tube-index-videos'
    channels: 'tube-index-channels'
    playlists: 'tube-index-playlists'

log:
  level: 'debug' # debug/info/warning/error

search-instance:
  name: 'Tube Search Index'

  # Set an image instead of displaying your website title in text at the top of the search page
  # Must be a relative URL. For example if you use a theme: /theme/mytheme/img/title.svg
  name_image: ''

  # The image between the title and the search bar
  search_image: ''

  description: 'A search engine of Tube videos and channels, developed by Framasoft'
  legal_notices_url: ''
  theme: 'default'

instances-index:
  # Contains Tube instance hosts the indexer will index
  # Must answer the following format: https://framagit.org/framasoft/tube/instances-tube#tube-auto-follow-global-search
  url: 'https://instances.joinpeertube.org/api/v1/instances/hosts'

  # A public URL that will be displayed in the search page
  # So your users can see what instances your search instance indexed
  public_url: 'https://instances.joinpeertube.org'

  # Useful to do tests
  whitelist:
    enabled: false
    hosts: null

videos-search:
  # Allow client to send browser language to boost results score that are in these languages
  boost-languages:
    enabled: true

  # Add ability to change videos search fields boost value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  # If boost == 0, the field will not be part of the search
  search-fields:
    name:
      boost: 5
    description:
      boost: 1
    tags:
      boost: 2
    account-display-name:
      boost: 2
    channel-display-name:
      boost: 2

channels-search:
  # Add ability to change channels search fields boost value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  # If boost == 0, the field will not be part of the search
  search-fields:
    name:
      boost: 5
    description:
      boost: 1
    display-name:
      boost: 3
    account-display-name:
      boost: 2

playlists-search:
  # Add ability to change playlists search fields boost value
  # See https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-multi-match-query.html for more information
  # If boost == 0, the field will not be part of the search
  search-fields:
    display-name:
      boost: 5
    description:
      boost: 1

api:
  # Blacklist hosts that will not be returned by the search API
  blacklist:
    enabled: false
    # Array of hosts
    hosts: null
