elastic-search:
  indexes:
    videos: 'tube-index-videos-test1'
    channels: 'tube-index-channels-test1'
    playlists: 'tube-index-playlists-test1'

search-instance:
  name_image: '/theme/framasoft/img/title.svg'
  search_image: '/theme/framasoft/img/sepia-search.svg'
  theme: 'framasoft'

videos-search:
  boost-languages:
    enabled: true

instances-index:
  whitelist:
    enabled: true
    hosts:
      - 'tube.cpy.re'
      - 'peertube2.cpy.re'
      - 'peertube3.cpy.re'
      - 'framatube.org'
      - 'aperi.tube'
      - 'tube.datagueule.tv'
      - 'thinkerview.video'
      - 'replay.jres.org'
      - 'tube.nah.re'
      - 'tube.parleur.net'
      - 'video.passageenseine.fr'

api:
  blacklist:
    enabled: true
    hosts:
      - 'tube.cpy.re'
