input_dir: ../../Chat/
output_dir: ../../Chat/Generated/
ib:  
  inputs:
    - ../Tools/Templates/buildable/
    - Modules/
  filter: ^((?!(DeactivateAccountViewController|Security)).)*\.(storyboard)
  outputs:
    templateName: scenes-swift4
    output: Storyboards.swift
strings:
  inputs: Assets/en.lproj/Vector.strings
  outputs:
    templatePath: Templates/Strings/flat-swift4-vector.stencil
    output: Strings.swift
    params:
      className: VectorL10n
      publicAccess: true
xcassets:  
  inputs:
    - Assets/Images.xcassets
    - Assets/SharedImages.xcassets
  outputs:
    templateName: swift4
    output: Images.swift
plist:
  inputs: Assets/Chat-Defaults.plist
  outputs:
    templateName: runtime-swift4
    output: ChatDefaults.swift
    params:
      enumName: ChatDefaults
