signing_id: releases@chat.imzqqq
subprojects:
    element-web:
        includeByDefault: true
        # Because element-web is not in our dependencies, but the versions
        # follow those of this project (well, vice-versa really)
        mirrorVersion: true
