listen:
  port: 3232

webserver:
  https: false
  hostname: 'localhost'
  port: 3232

database:
  hostname: 'localhost'
  port: 5432
  name: 'peertube_instances'
  username: 'tube'
  password: 'tube'

log:
  level: 'debug' # debug/info/warning/error

instance:
  client-warning: >
    This is a warning
