[book]
authors = ["imqzzZ"]
language = "en"
multilingual = false
src = "."
title = "maubot"
site-url = "/maubot/"

[build]
build-dir = "../dist/maubot"

[preprocessor.links]

[output.html]
git-repository-url = "https://github.com/mautrix/docs"
git-repository-icon = "fa-github"
theme = "../theme/maubot"

[output.linkcheck]
optional = true
user-agent = "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
cache-timeout = 604800
exclude = [ "http://localhost:29316" ]
traverse-parent-directories = false
