on:
  push:
    branches:    
      - 'v2'
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      MICROBLOGPUB_CONFIG_FILE: tests.toml
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: |
        poetry env use "3.10"
        poetry install --no-interaction
    - run: poetry run inv lint
    - run: poetry run inv tests
