name: Build docs

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.11'

      - run: mdbook build

      - name: Deploy latest
        uses: peaceiris/actions-gh-pages@v3
        # Only push if this is main, otherwise we just want to build
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keep_files: true
          publish_dir: ./book
          destination_dir: ./latest
