version: "3"

services:
  server:
    image: microblogpub/microblogpub:latest 
    container_name: microblogpub
    user: 1000:1000
    restart: always
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
