#!/bin/sh

# PROVIDE: tube
# REQUIRE: LOGIN postgresql nginx redis
# KEYWORD: shutdown

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

. /etc/rc.subr

desc="Peertube daemon"
name=tube
rcvar=peertube_enable

load_rc_config $name

: ${peertube_enable:=NO}

sig_stop=-KILL
peertube_chdir="/var/www/tube/tube-latest"
peertube_env="HOME=/var/www/tube \
NODE_ENV=production \
NODE_CONFIG_DIR=/var/www/tube/config \
USER=tube"
peertube_user=tube

command="/usr/local/bin/node"
command_args="dist/server >> /var/log/tube/${name}.log 2>&1 &"

run_rc_command "$1"
