options:
  merge-default-rules: false
  formatter: html
  max-warnings: 50

files:
  include: 'src/style/**/*.sass'

rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations:
    - 2
    - exclude:
        - breakpoint
        - mq
  no-warn: 1
  no-debug: 1
  hex-notation:
    - 2
    - style: uppercase
  indentation:
    - 2
    - size: 4
  property-sort-order:
    - 0
