version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    reviewers:
      - "gabek"
    ignore:
          # Ignore patch updates from some libraries
          - dependency-name: "*typescript*"
            update-types: ["version-update:semver-patch"]
          - dependency-name: "*eslint*"
            update-types: ["version-update:semver-patch"]
          - dependency-name: "@types/*"
            update-types: ["version-update:semver-patch"]
