name: Chat
attributes:
  ORGANIZATIONNAME: imqzzZ

configs:
  Debug: debug
  Release: release

fileGroups:
    - README.md
    - Podfile
    - project.yml

configFiles:
  Debug: Config/Project-Debug.xcconfig
  Release: Config/Project-Release.xcconfig

options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  createIntermediateGroups: true
  useBaseInternationalization: true
  postGenCommand: sh Tools/XcodeGen/postGenCommand.sh
    
include:
  - path: Chat/target.yml
  - path: ChatTests/target.yml
  - path: ChatShareExtension/target.yml
  - path: SiriIntents/target.yml
  - path: ChatNSE/target.yml
  - path: DesignKit/target.yml
  - path: ChatSwiftUI/target.yml
  - path: ChatSwiftUI/targetUnitTests.yml
  - path: ChatSwiftUI/targetUITests.yml

packages:
  SDWebImage:
    from: 5.12.3
    url: https://github.com/SDWebImage/SDWebImage.git
  ServiceLayer:
    path: ./Chat/Flow/ServiceLayer
  BlurHash:
    path: ./Chat/Flow/BlurHash
  ViewModels:
    path: ./Chat/Flow/ViewModels
  Secrets:
    path: ./Chat/Flow/Secrets
  MastodonAPI:
    path: ./Chat/Flow/MastodonAPI
  Mastodon:
    path: ./Chat/Flow/Mastodon
  Keychain:
    path: ./Chat/Flow/Keychain
  HTTP:
    path: ./Chat/Flow/HTTP
  DB:
    path: ./Chat/Flow/DB
  Base16:
    path: ./Chat/Flow/Base16
  CodableBloomFilter:
    path: ./Chat/Flow/CodableBloomFilter
  CombineExpectations:
    path: ./Chat/Flow/CombineExpectations
  GRDB:
    path: ./Chat/Flow/GRDB
