name: linter

# This action works with pull requests and pushes
on: [push, pull_request]

jobs:
  format:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        
    - name: Linter
      uses: tj-actions/eslint-changed-files@v7.3
      with:
        config_path: '.eslintrc.js'
        ignore_path: '.eslintignore'
        extensions: 'ts,tsx,js,jsx'
