blank_issues_enabled: true
contact_links:
 - name: Chat Spec Discussion
   url: "https://to.chat.imzqqq.top/#/#matrix-spec:chat.imzqqq.top"
   about: Questions about the spec and proposal process can be asked here.
 - name: Chat Security Policy
   url: https://www.chat.imzqqq.top/security-disclosure-policy/
   about: Learn more about our security disclosure policy.
